CREATE TABLE IF NOT EXISTS public."Airports"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Country" character varying(36) COLLATE pg_catalog."default",
    "City" character varying(36) COLLATE pg_catalog."default",
    CONSTRAINT "Airports_pkey" PRIMARY KEY ("Id")
)

CREATE TABLE IF NOT EXISTS public."Bookings"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Booked" boolean,
    "FlightId" bigint,
    CONSTRAINT "Bookings_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Bookings_FlightId_FK" FOREIGN KEY ("FlightId")
        REFERENCES public."Flights" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

CREATE TABLE IF NOT EXISTS public."Flights"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "AirportIdFrom" bigint NOT NULL,
    "AirportIdTo" bigint NOT NULL,
    "DepartureDate" timestamp with time zone,
    "ArrivalDate" timestamp with time zone,
    "Completed" boolean,
    CONSTRAINT "Flights_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "ArrivalDate" UNIQUE ("ArrivalDate"),
    CONSTRAINT "DepartureDate" UNIQUE ("DepartureDate")
        INCLUDE("DepartureDate"),
    CONSTRAINT "Flights_AirportIdFrom_FK" FOREIGN KEY ("AirportIdFrom")
        REFERENCES public."Airports" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "Flights_AirpostIdTo_FK" FOREIGN KEY ("AirportIdTo")
        REFERENCES public."Airports" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

CREATE TABLE IF NOT EXISTS public."Tickets"
(
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Passanger" character varying(36) COLLATE pg_catalog."default",
    "DepartureId" bigint NOT NULL,
    "ArrivalId" bigint NOT NULL,
    "BookingId" bigint NOT NULL,
    "CheckedIn" boolean,
    "FlightId" bigint NOT NULL,
    "Price" bigint NOT NULL DEFAULT 0,
    CONSTRAINT "Tickets_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Tickets_ArrivalId_FK" FOREIGN KEY ("ArrivalId")
        REFERENCES public."Airports" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "Tickets_BookingId_FK" FOREIGN KEY ("BookingId")
        REFERENCES public."Bookings" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "Tickets_DepartureId_FK" FOREIGN KEY ("DepartureId")
        REFERENCES public."Airports" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "Tickets_FlightId_FK" FOREIGN KEY ("FlightId")
        REFERENCES public."Flights" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)